install.packages("devtools")
devtools::install_github("balexanderstats/ggsurvey")
install_github("allisonhorst/palmerpenguins")
install.packages("survey")
install.packages("srvyr")
install_github("jamesmartherus/anesr")
install.packages("knitr")
